# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bakemcp < Formula
  desc "Turn any OpenAPI 3.x spec into a ready-to-run MCP server"
  homepage "https://github.com/stefanoMat/bakemcp"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stefanoMat/bakemcp/releases/download/v0.2.1/bakemcp_darwin_amd64.tar.gz"
      sha256 "435bb3f308abca8a03bb6eccfb5df0536c39a8d9a4d83681b27afb10d632323f"

      def install
        bin.install "bakemcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stefanoMat/bakemcp/releases/download/v0.2.1/bakemcp_darwin_arm64.tar.gz"
      sha256 "4da2037beca030a1fee373342174789fbced056178c4697557c7716ae39a0e41"

      def install
        bin.install "bakemcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanoMat/bakemcp/releases/download/v0.2.1/bakemcp_linux_amd64.tar.gz"
      sha256 "0b503ec1751065a43e0b21a213f0f72fb9fd39144ab4aa078a697380f71840d0"
      def install
        bin.install "bakemcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanoMat/bakemcp/releases/download/v0.2.1/bakemcp_linux_arm64.tar.gz"
      sha256 "e9bba5d7382ca8aaf5d9f6c5db536c2a30f8ec94002c6f3c65151a37a05dc575"
      def install
        bin.install "bakemcp"
      end
    end
  end

  test do
    system "#{bin}/bakemcp", "--help"
  end
end
