# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bakemcp < Formula
  desc "Turn any OpenAPI 3.x spec into a ready-to-run MCP server"
  homepage "https://github.com/stefanoMat/bakemcp"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stefanoMat/bakemcp/releases/download/v0.2.2/bakemcp_darwin_amd64.tar.gz"
      sha256 "836471eaf0af09d95db7174578ccac767ef6a8b97a68fd7d19f161b6b3d52a93"

      def install
        bin.install "bakemcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stefanoMat/bakemcp/releases/download/v0.2.2/bakemcp_darwin_arm64.tar.gz"
      sha256 "4e4d5d19193a3236d70cbafd506224a900fb96b1aec5c2e8080cd883bb8aee1e"

      def install
        bin.install "bakemcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanoMat/bakemcp/releases/download/v0.2.2/bakemcp_linux_amd64.tar.gz"
      sha256 "7aabd434eafac150bf651072adcc79ea9fde0f227d91b915802173a0fb00d8cb"
      def install
        bin.install "bakemcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanoMat/bakemcp/releases/download/v0.2.2/bakemcp_linux_arm64.tar.gz"
      sha256 "dc3b087b28e5f447dfd46908079095430954574bf44bff9b967567845ceddb2e"
      def install
        bin.install "bakemcp"
      end
    end
  end

  test do
    system "#{bin}/bakemcp", "--help"
  end
end
